import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
// import { GoogleTagManager } from "@next/third-parties/google";
import GTM from "./GoogleTagManager";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  verification: {
    google: "mfwlEiByrlXMK0tUpetiTALmWJubYqgCgGgyVNq8VGw",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <GTM />
      </body>
      {/* <GoogleTagManager gtmId="GTM-MJ3629V5" /> */}
    </html>
  );
}
